version: "3"
services:
  wealthi-db:
    image: postgres
    restart: always
    container_name: weekday-calculator-db
    environment:
      - POSTGRES_DB=postgres
      - PGHOST=localhost
      - PGPORT=4501
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Password123!
    ports:
      - 4501:4501
    volumes:
      - ./postgres-data:/var/lib/postgresql/data